// Generated by cli-to-js — https://github.com/aidenybai/cli-to-js

import { spawn } from "node:child_process";

interface CommandResult {
  stdout: string;
  stderr: string;
  exitCode: number;
}

const BINARY = "git";

const toArgs = (options: Record<string, unknown>): string[] => {
  const flagArgs: string[] = [];
  const positionalArgs: string[] = [];
  for (const [key, value] of Object.entries(options)) {
    if (key === "_") {
      if (value == null) continue;
      const pos = Array.isArray(value) ? value : [value];
      positionalArgs.push(...pos.map(String));
      continue;
    }
    const flag = key.startsWith("-")
      ? key
      : key.length <= 1
        ? `-${key}`
        : `--${key
            .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
            .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
            .toLowerCase()}`;
    if (typeof value === "boolean") {
      if (value) flagArgs.push(flag);
    } else if (Array.isArray(value)) {
      for (const item of value) flagArgs.push(flag, String(item));
    } else if (value != null) {
      flagArgs.push(flag, String(value));
    }
  }
  return [...flagArgs, ...positionalArgs];
};

const run = (subcommand: string[], options: Record<string, unknown> = {}): Promise<CommandResult> =>
  new Promise((resolve, reject) => {
    const stdoutChunks: Buffer[] = [];
    const stderrChunks: Buffer[] = [];
    let spawnError: Error | null = null;
    const child = spawn(BINARY, [...subcommand, ...toArgs(options)], { windowsHide: true });
    child.stdout?.on("data", (chunk: Buffer) => stdoutChunks.push(chunk));
    child.stderr?.on("data", (chunk: Buffer) => stderrChunks.push(chunk));
    child.on("error", (error) => {
      spawnError = error;
    });
    child.on("close", (exitCode) => {
      if (spawnError) {
        reject(spawnError);
        return;
      }
      resolve({
        stdout: Buffer.concat(stdoutChunks).toString("utf-8"),
        stderr: Buffer.concat(stderrChunks).toString("utf-8"),
        exitCode: exitCode ?? 1,
      });
    });
  });

interface CloneOptions {
  /** be more verbose */
  verbose?: boolean;
  /** be more quiet */
  quiet?: boolean;
  /** force progress reporting */
  progress?: boolean;
  /** don't clone shallow repository */
  rejectShallow?: boolean;
  /** don't create a checkout */
  noCheckout?: boolean;
  /** create a bare repository */
  bare?: boolean;
  /** create a mirror repository (implies bare) */
  mirror?: boolean;
  /** to clone from a local repository */
  local?: boolean;
  /** don't use local hardlinks, always copy */
  noHardlinks?: boolean;
  /** setup as shared repository */
  shared?: boolean;
  recurseSubmodules?: boolean;
  recursive?: boolean;
  /** number of submodules cloned in parallel */
  jobs?: string;
  template?: string;
  /** reference repository */
  reference?: string;
  referenceIfAble?: string;
  /** use --reference only while cloning */
  dissociate?: boolean;
  /** use <name> instead of 'origin' to track upstream */
  origin?: string;
  branch?: string;
  uploadPack?: string;
  /** create a shallow clone of that depth */
  depth?: string;
  shallowSince?: string;
  shallowExclude?: string;
  /** clone only one branch, HEAD or --branch */
  singleBranch?: boolean;
  /** don't clone any tags, and make later fetches not to follow them */
  noTags?: boolean;
  /** any cloned submodules will be shallow */
  shallowSubmodules?: boolean;
  separateGitDir?: string;
  config?: string;
  serverOption?: string;
  /** use IPv4 addresses only */
  ipv4?: boolean;
  /** use IPv6 addresses only */
  ipv6?: boolean;
  /** object filtering */
  filter?: string;
  alsoFilterSubmodules?: boolean;
  /** any cloned submodules will use their remote-tracking branch */
  remoteSubmodules?: boolean;
  /** initialize sparse-checkout file to include only files at root */
  sparse?: boolean;
  /** a URI for downloading bundles before fetching from origin remote */
  bundleUri?: string;
  _?: string | string[];
  [key: string]: unknown;
}

/** git clone
 * Clone a repository into a new directory
 */
export const clone = (options: CloneOptions = {}): Promise<CommandResult> =>
  run(["clone"], options);

interface InitOptions {
  template?: string;
  /** create a bare repository */
  bare?: boolean;
  shared?: boolean;
  /** be quiet */
  quiet?: boolean;
  separateGitDir?: string;
  initialBranch?: string;
  objectFormat?: string;
  _?: string | string[];
  [key: string]: unknown;
}

/** git init
 * Create an empty Git repository or reinitialize an existing one
 */
export const init = (options: InitOptions = {}): Promise<CommandResult> => run(["init"], options);

interface AddOptions {
  /** dry run */
  dryRun?: boolean;
  /** be verbose */
  verbose?: boolean;
  /** interactive picking */
  interactive?: boolean;
  /** select hunks interactively */
  patch?: boolean;
  /** edit current diff and apply */
  edit?: boolean;
  /** allow adding otherwise ignored files */
  force?: boolean;
  /** update tracked files */
  update?: boolean;
  /** renormalize EOL of tracked files (implies -u) */
  renormalize?: boolean;
  /** record only the fact that the path will be added later */
  intentToAdd?: boolean;
  /** add changes from all tracked and untracked files */
  all?: boolean;
  /** ignore paths removed in the working tree (same as --no-all) */
  ignoreRemoval?: boolean;
  /** don't add, only refresh the index */
  refresh?: boolean;
  /** just skip files which cannot be added because of errors */
  ignoreErrors?: boolean;
  /** check if - even missing - files are ignored in dry run */
  ignoreMissing?: boolean;
  /** allow updating entries outside of the sparse-checkout cone */
  sparse?: boolean;
  /** override the executable bit of the listed files */
  chmod?: boolean;
  pathspecFromFile?: string;
  /** with --pathspec-from-file, pathspec elements are separated with NUL character */
  pathspecFileNul?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git add
 * Add file contents to the index
 */
export const add = (options: AddOptions = {}): Promise<CommandResult> => run(["add"], options);

interface MvOptions {
  /** be verbose */
  verbose?: boolean;
  /** dry run */
  dryRun?: boolean;
  /** force move/rename even if target exists */
  force?: boolean;
  /** skip move/rename errors */
  k?: boolean;
  /** allow updating entries outside of the sparse-checkout cone */
  sparse?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git mv
 * Move or rename a file, a directory, or a symlink
 */
export const mv = (options: MvOptions = {}): Promise<CommandResult> => run(["mv"], options);

interface RestoreOptions {
  source?: string;
  /** restore the index */
  staged?: boolean;
  /** restore the working tree (default) */
  worktree?: boolean;
  /** ignore unmerged entries */
  ignoreUnmerged?: boolean;
  /** use overlay mode */
  overlay?: boolean;
  /** suppress progress reporting */
  quiet?: boolean;
  recurseSubmodules?: boolean;
  /** force progress reporting */
  progress?: boolean;
  /** perform a 3-way merge with the new branch */
  merge?: boolean;
  /** conflict style (merge, diff3, or zdiff3) */
  conflict?: string;
  /** checkout our version for unmerged files */
  ours?: boolean;
  /** checkout their version for unmerged files */
  theirs?: boolean;
  /** select hunks interactively */
  patch?: boolean;
  ignoreSkipWorktreeBits?: boolean;
  pathspecFromFile?: string;
  /** with --pathspec-from-file, pathspec elements are separated with NUL character */
  pathspecFileNul?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git restore
 * Restore working tree files
 */
export const restore = (options: RestoreOptions = {}): Promise<CommandResult> =>
  run(["restore"], options);

interface RmOptions {
  /** dry run */
  dryRun?: boolean;
  /** do not list removed files */
  quiet?: boolean;
  /** only remove from the index */
  cached?: boolean;
  /** override the up-to-date check */
  force?: boolean;
  /** allow recursive removal */
  r?: boolean;
  /** exit with a zero status even if nothing matched */
  ignoreUnmatch?: boolean;
  /** allow updating entries outside of the sparse-checkout cone */
  sparse?: boolean;
  pathspecFromFile?: string;
  /** with --pathspec-from-file, pathspec elements are separated with NUL character */
  pathspecFileNul?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git rm
 * Remove files from the working tree and from the index
 */
export const rm = (options: RmOptions = {}): Promise<CommandResult> => run(["rm"], options);

/** git bisect
 * Use binary search to find the commit that introduced a bug
 */
export const bisect = (options: Record<string, unknown> = {}): Promise<CommandResult> =>
  run(["bisect"], options);

interface DiffOptions {
  /** output diff-raw with lines terminated with NUL. */
  z?: boolean;
  /** output patch format. */
  p?: boolean;
  /** synonym for -p. */
  u?: boolean;
  /**  output both a patch and the diff-raw format. */
  patchWithRaw?: boolean;
  /** show diffstat instead of patch. */
  stat?: boolean;
  /** show numeric diffstat instead of patch. */
  numstat?: boolean;
  /**  output a patch and prepend its diffstat. */
  patchWithStat?: boolean;
  /** show only names of changed files. */
  nameOnly?: boolean;
  nameStatus?: string;
  /** show full object name on index lines. */
  fullIndex?: boolean;
  /** abbreviate object names in diff-tree header and diff-raw. */
  abbrev?: string;
  /** swap input file pairs. */
  R?: boolean;
  /** detect complete rewrites. */
  B?: boolean;
  /** detect renames. */
  M?: boolean;
  /** detect copies. */
  C?: boolean;
  /**  try unchanged files as candidate for copy detection. */
  findCopiesHarder?: boolean;
  /** limit rename attempts up to <n> paths. */
  l?: boolean;
  /** reorder diffs according to the <file>. */
  O?: boolean;
  /** find filepair whose only one side contains the string. */
  S?: boolean;
  /**  show all files diff when -S is used and hit is found. */
  pickaxeAll?: boolean;
  /** --text    treat all files as text. */
  a?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git diff
 * Show changes between commits, commit and working tree, etc
 */
export const diff = (options: DiffOptions = {}): Promise<CommandResult> => run(["diff"], options);

interface GrepOptions {
  /** search in index instead of in the work tree */
  cached?: boolean;
  /** find in contents not managed by git */
  noIndex?: boolean;
  /** search in both tracked and untracked files */
  untracked?: boolean;
  /** ignore files specified via '.gitignore' */
  excludeStandard?: boolean;
  /** recursively search in each submodule */
  recurseSubmodules?: boolean;
  /** show non-matching lines */
  invertMatch?: boolean;
  /** case insensitive matching */
  ignoreCase?: boolean;
  /** match patterns only at word boundaries */
  wordRegexp?: boolean;
  /** process binary files as text */
  text?: boolean;
  /** don't match patterns in binary files */
  I?: boolean;
  /** process binary files with textconv filters */
  textconv?: boolean;
  /** search in subdirectories (default) */
  recursive?: boolean;
  /** descend at most <depth> levels */
  maxDepth?: string;
  extendedRegexp?: boolean;
  /** use basic POSIX regular expressions (default) */
  basicRegexp?: boolean;
  /** interpret patterns as fixed strings */
  fixedStrings?: boolean;
  /** use Perl-compatible regular expressions */
  perlRegexp?: boolean;
  /** show line numbers */
  lineNumber?: boolean;
  /** show column number of first match */
  column?: boolean;
  /** show filenames */
  H?: boolean;
  /** show filenames relative to top directory */
  fullName?: boolean;
  filesWithMatches?: boolean;
  /** synonym for --files-with-matches */
  nameOnly?: boolean;
  filesWithoutMatch?: boolean;
  /** print NUL after filenames */
  null?: boolean;
  /** show only matching parts of a line */
  onlyMatching?: boolean;
  /** show the number of matches instead of matching lines */
  count?: boolean;
  /** highlight matches */
  color?: boolean;
  /** print empty line between matches from different files */
  break?: boolean;
  /** show filename only once above matches from same file */
  heading?: boolean;
  /** show <n> context lines before and after matches */
  context?: string;
  beforeContext?: string;
  afterContext?: string;
  /** use <n> worker threads */
  threads?: string;
  /** shortcut for -C NUM */
  N?: boolean;
  /** show a line with the function name before matches */
  showFunction?: boolean;
  functionContext?: boolean;
  /** read patterns from file */
  f?: string;
  /** match <pattern> */
  e?: string;
  /** combine patterns specified with -e */
  and?: boolean;
  or?: boolean;
  not?: boolean;
  /** indicate hit with exit status without output */
  quiet?: boolean;
  /** show only matches from files that match all patterns */
  allMatch?: boolean;
  openFilesInPager?: boolean;
  /** allow calling of grep(1) (ignored by this build) */
  extGrep?: boolean;
  /** maximum number of results per file */
  maxCount?: string;
  _?: string | string[];
  [key: string]: unknown;
}

/** git grep
 * Print lines matching a pattern
 */
export const grep = (options: GrepOptions = {}): Promise<CommandResult> => run(["grep"], options);

interface LogOptions {
  /** suppress diff output */
  quiet?: boolean;
  /** show source */
  source?: boolean;
  /** use mail map file */
  useMailmap?: boolean;
  /** alias of --use-mailmap */
  mailmap?: boolean;
  /** clear all previously-defined decoration filters */
  clearDecorations?: boolean;
  decorateRefs?: string;
  decorateRefsExclude?: string;
  /** decorate options */
  decorate?: boolean;
  /** trace the evolution of line range <start>,<end> or function :<funcname> in <file> */
  L?: string;
  _?: string | string[];
  [key: string]: unknown;
}

/** git log
 * Show commit logs
 */
export const log = (options: LogOptions = {}): Promise<CommandResult> => run(["log"], options);

interface ShowOptions {
  /** suppress diff output */
  quiet?: boolean;
  /** show source */
  source?: boolean;
  /** use mail map file */
  useMailmap?: boolean;
  /** alias of --use-mailmap */
  mailmap?: boolean;
  /** clear all previously-defined decoration filters */
  clearDecorations?: boolean;
  decorateRefs?: string;
  decorateRefsExclude?: string;
  /** decorate options */
  decorate?: boolean;
  /** trace the evolution of line range <start>,<end> or function :<funcname> in <file> */
  L?: string;
  _?: string | string[];
  [key: string]: unknown;
}

/** git show
 * Show various types of objects
 */
export const show = (options: ShowOptions = {}): Promise<CommandResult> => run(["show"], options);

interface StatusOptions {
  /** be verbose */
  verbose?: boolean;
  /** show status concisely */
  short?: boolean;
  /** show branch information */
  branch?: boolean;
  /** show stash information */
  showStash?: boolean;
  /** compute full ahead/behind values */
  aheadBehind?: boolean;
  porcelain?: boolean;
  /** show status in long format (default) */
  long?: boolean;
  /** terminate entries with NUL */
  null?: boolean;
  untrackedFiles?: boolean;
  /** show ignored files, optional modes: traditional, matching, no. (Default: traditional) */
  ignored?: boolean;
  ignoreSubmodules?: boolean;
  /** list untracked files in columns */
  column?: boolean;
  /** do not detect renames */
  noRenames?: boolean;
  findRenames?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git status
 * Show the working tree status
 */
export const status = (options: StatusOptions = {}): Promise<CommandResult> =>
  run(["status"], options);

interface BranchOptions {
  /** show hash and subject, give twice for upstream branch */
  verbose?: boolean;
  /** suppress informational messages */
  quiet?: boolean;
  track?: boolean;
  setUpstreamTo?: string;
  /** unset the upstream info */
  unsetUpstream?: boolean;
  /** use colored output */
  color?: boolean;
  /** act on remote-tracking branches */
  remotes?: boolean;
  /** print only branches that contain the commit */
  contains?: string;
  noContains?: string;
  /** use <n> digits to display object names */
  abbrev?: boolean;
  /** list both remote-tracking and local branches */
  all?: boolean;
  /** delete fully merged branch */
  delete?: boolean;
  /** delete branch (even if not merged) */
  D?: boolean;
  /** move/rename a branch and its reflog */
  move?: boolean;
  /** move/rename a branch, even if target exists */
  M?: boolean;
  /** do not output a newline after empty formatted refs */
  omitEmpty?: boolean;
  /** copy a branch and its reflog */
  copy?: boolean;
  /** copy a branch, even if target exists */
  C?: boolean;
  /** list branch names */
  list?: boolean;
  /** show current branch name */
  showCurrent?: boolean;
  /** create the branch's reflog */
  createReflog?: boolean;
  /** edit the description for the branch */
  editDescription?: boolean;
  /** force creation, move/rename, deletion */
  force?: boolean;
  /** print only branches that are merged */
  merged?: string;
  /** print only branches that are not merged */
  noMerged?: string;
  /** list branches in columns */
  column?: boolean;
  /** field name to sort on */
  sort?: string;
  /** print only branches of the object */
  pointsAt?: string;
  /** sorting and filtering are case insensitive */
  ignoreCase?: boolean;
  /** recurse through submodules */
  recurseSubmodules?: boolean;
  /** format to use for the output */
  format?: string;
  _?: string | string[];
  [key: string]: unknown;
}

/** git branch
 * List, create, or delete branches
 */
export const branch = (options: BranchOptions = {}): Promise<CommandResult> =>
  run(["branch"], options);

interface CommitOptions {
  /** suppress summary after successful commit */
  quiet?: boolean;
  /** show diff in commit message template */
  verbose?: boolean;
  /** read message from file */
  file?: string;
  /** override author for commit */
  author?: string;
  /** override date for commit */
  date?: string;
  message?: string;
  reeditMessage?: string;
  reuseMessage?: string;
  fixup?: boolean;
  /** use autosquash formatted message to squash specified commit */
  squash?: string;
  /** the commit is authored by me now (used with -C/-c/--amend) */
  resetAuthor?: boolean;
  /** add custom trailer(s) */
  trailer?: string;
  /** add a Signed-off-by trailer */
  signoff?: boolean;
  template?: string;
  /** force edit of commit */
  edit?: boolean;
  /** how to strip spaces and #comments from message */
  cleanup?: string;
  /** include status in commit message template */
  status?: boolean;
  gpgSign?: boolean;
  /** commit all changed files */
  all?: boolean;
  /** add specified files to index for commit */
  include?: boolean;
  /** interactively add files */
  interactive?: boolean;
  /** interactively add changes */
  patch?: boolean;
  /** commit only specified files */
  only?: boolean;
  /** bypass pre-commit and commit-msg hooks */
  noVerify?: boolean;
  /** show what would be committed */
  dryRun?: boolean;
  /** show status concisely */
  short?: boolean;
  /** show branch information */
  branch?: boolean;
  /** compute full ahead/behind values */
  aheadBehind?: boolean;
  /** machine-readable output */
  porcelain?: boolean;
  /** show status in long format (default) */
  long?: boolean;
  /** terminate entries with NUL */
  null?: boolean;
  /** amend previous commit */
  amend?: boolean;
  /** bypass post-rewrite hook */
  noPostRewrite?: boolean;
  untrackedFiles?: boolean;
  pathspecFromFile?: string;
  /** with --pathspec-from-file, pathspec elements are separated with NUL character */
  pathspecFileNul?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git commit
 * Record changes to the repository
 */
export const commit = (options: CommitOptions = {}): Promise<CommandResult> =>
  run(["commit"], options);

interface MergeOptions {
  /** do not show a diffstat at the end of the merge */
  n?: boolean;
  /** show a diffstat at the end of the merge */
  stat?: boolean;
  /** (synonym to --stat) */
  summary?: boolean;
  /** add (at most <n>) entries from shortlog to merge commit message */
  log?: boolean;
  /** create a single commit instead of doing a merge */
  squash?: boolean;
  /** perform a commit if the merge succeeds (default) */
  commit?: boolean;
  /** edit message before committing */
  edit?: boolean;
  /** how to strip spaces and #comments from message */
  cleanup?: string;
  /** allow fast-forward (default) */
  ff?: boolean;
  /** abort if fast-forward is not possible */
  ffOnly?: boolean;
  /** update the index with reused conflict resolution if possible */
  rerereAutoupdate?: boolean;
  /** verify that the named commit has a valid GPG signature */
  verifySignatures?: boolean;
  strategy?: string;
  strategyOption?: string;
  message?: string;
  /** read message from file */
  file?: string;
  /** use <name> instead of the real target */
  intoName?: string;
  /** be more verbose */
  verbose?: boolean;
  /** be more quiet */
  quiet?: boolean;
  /** abort the current in-progress merge */
  abort?: boolean;
  /** --abort but leave index and working tree alone */
  quit?: boolean;
  /** continue the current in-progress merge */
  continue?: boolean;
  allowUnrelatedHistories?: boolean;
  /** force progress reporting */
  progress?: boolean;
  gpgSign?: boolean;
  /** automatically stash/stash pop before and after */
  autostash?: boolean;
  /** update ignored files (default) */
  overwriteIgnore?: boolean;
  /** add a Signed-off-by trailer */
  signoff?: boolean;
  /** bypass pre-merge-commit and commit-msg hooks */
  noVerify?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git merge
 * Join two or more development histories together
 */
export const merge = (options: MergeOptions = {}): Promise<CommandResult> =>
  run(["merge"], options);

interface RebaseOptions {
  /** rebase onto given branch instead of upstream */
  onto?: string;
  /** use the merge-base of upstream and branch as the current base */
  keepBase?: boolean;
  /** allow pre-rebase hook to run */
  noVerify?: boolean;
  /** be quiet. implies --no-stat */
  quiet?: boolean;
  /** display a diffstat of what changed upstream */
  verbose?: boolean;
  /** do not show diffstat of what changed upstream */
  noStat?: boolean;
  /** add a Signed-off-by trailer to each commit */
  signoff?: boolean;
  committerDateIsAuthorDate?: boolean;
  /** ignore author date and use current date */
  resetAuthorDate?: boolean;
  /** passed to 'git apply' */
  C?: string;
  /** ignore changes in whitespace */
  ignoreWhitespace?: boolean;
  whitespace?: string;
  /** cherry-pick all commits, even if unchanged */
  forceRebase?: boolean;
  /** cherry-pick all commits, even if unchanged */
  noFf?: boolean;
  /** continue */
  continue?: boolean;
  /** skip current patch and continue */
  skip?: boolean;
  /** abort and check out the original branch */
  abort?: boolean;
  /** abort but keep HEAD where it is */
  quit?: boolean;
  /** edit the todo list during an interactive rebase */
  editTodo?: boolean;
  /** show the patch file being applied or merged */
  showCurrentPatch?: boolean;
  /** use apply strategies to rebase */
  apply?: boolean;
  /** use merging strategies to rebase */
  merge?: boolean;
  /** let the user edit the list of commits to rebase */
  interactive?: boolean;
  /** update the index with reused conflict resolution if possible */
  rerereAutoupdate?: boolean;
  empty?: boolean;
  /** move commits that begin with squash!/fixup! under -i */
  autosquash?: boolean;
  /** update branches that point to commits that are being rebased */
  updateRefs?: boolean;
  gpgSign?: boolean;
  /** automatically stash/stash pop before and after */
  autostash?: boolean;
  /** add exec lines after each commit of the editable list */
  exec?: string;
  rebaseMerges?: boolean;
  /** use 'merge-base --fork-point' to refine upstream */
  forkPoint?: boolean;
  strategy?: string;
  strategyOption?: string;
  /** rebase all reachable commits up to the root(s) */
  root?: boolean;
  rescheduleFailedExec?: boolean;
  reapplyCherryPicks?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git rebase
 * Reapply commits on top of another base tip
 */
export const rebase = (options: RebaseOptions = {}): Promise<CommandResult> =>
  run(["rebase"], options);

interface ResetOptions {
  /** be quiet, only report errors */
  quiet?: boolean;
  /** skip refreshing the index after reset */
  noRefresh?: boolean;
  /** reset HEAD and index */
  mixed?: boolean;
  /** reset only HEAD */
  soft?: boolean;
  /** reset HEAD, index and working tree */
  hard?: boolean;
  /** reset HEAD, index and working tree */
  merge?: boolean;
  /** reset HEAD but keep local changes */
  keep?: boolean;
  recurseSubmodules?: boolean;
  /** select hunks interactively */
  patch?: boolean;
  /** record only the fact that removed paths will be added later */
  intentToAdd?: boolean;
  pathspecFromFile?: string;
  /** with --pathspec-from-file, pathspec elements are separated with NUL character */
  pathspecFileNul?: boolean;
  /** DEPRECATED (use --pathspec-file-nul instead): paths are separated with NUL character */
  z?: boolean;
  /** DEPRECATED (use --pathspec-from-file=- instead): read paths from <stdin> */
  stdin?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git reset
 * Reset current HEAD to the specified state
 */
export const reset = (options: ResetOptions = {}): Promise<CommandResult> =>
  run(["reset"], options);

interface SwitchOptions {
  create?: string;
  forceCreate?: string;
  /** second guess 'git switch <no-such-branch>' */
  guess?: boolean;
  /** throw away local modifications */
  discardChanges?: boolean;
  /** suppress progress reporting */
  quiet?: boolean;
  recurseSubmodules?: boolean;
  /** force progress reporting */
  progress?: boolean;
  /** perform a 3-way merge with the new branch */
  merge?: boolean;
  /** conflict style (merge, diff3, or zdiff3) */
  conflict?: string;
  /** detach HEAD at named commit */
  detach?: boolean;
  track?: boolean;
  /** force checkout (throw away local modifications) */
  force?: boolean;
  orphan?: string;
  /** update ignored files (default) */
  overwriteIgnore?: boolean;
  ignoreOtherWorktrees?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git switch
 * Switch branches
 */
export const switchBranch = (options: SwitchOptions = {}): Promise<CommandResult> =>
  run(["switch"], options);

interface TagOptions {
  /** list tag names */
  list?: boolean;
  /** print <n> lines of each tag message */
  n?: boolean;
  /** delete tags */
  delete?: boolean;
  /** verify tags */
  verify?: boolean;
  /** annotated tag, needs a message */
  annotate?: boolean;
  message?: string;
  /** read message from file */
  file?: string;
  /** force edit of tag message */
  edit?: boolean;
  /** annotated and GPG-signed tag */
  sign?: boolean;
  /** how to strip spaces and #comments from message */
  cleanup?: string;
  localUser?: string;
  /** replace the tag if exists */
  force?: boolean;
  /** create a reflog */
  createReflog?: boolean;
  /** show tag list in columns */
  column?: boolean;
  /** print only tags that contain the commit */
  contains?: string;
  noContains?: string;
  /** print only tags that are merged */
  merged?: string;
  /** print only tags that are not merged */
  noMerged?: string;
  /** do not output a newline after empty formatted refs */
  omitEmpty?: boolean;
  /** field name to sort on */
  sort?: string;
  /** print only tags of the object */
  pointsAt?: string;
  /** format to use for the output */
  format?: string;
  /** respect format colors */
  color?: boolean;
  /** sorting and filtering are case insensitive */
  ignoreCase?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git tag
 * Create, list, delete or verify a tag object signed with GPG
 */
export const tag = (options: TagOptions = {}): Promise<CommandResult> => run(["tag"], options);

interface FetchOptions {
  /** be more verbose */
  verbose?: boolean;
  /** be more quiet */
  quiet?: boolean;
  /** fetch from all remotes */
  all?: boolean;
  /** set upstream for git pull/fetch */
  setUpstream?: boolean;
  /** append to .git/FETCH_HEAD instead of overwriting */
  append?: boolean;
  /** use atomic transaction to update references */
  atomic?: boolean;
  /** path to upload pack on remote end */
  uploadPack?: string;
  /** force overwrite of local reference */
  force?: boolean;
  /** fetch from multiple remotes */
  multiple?: boolean;
  /** fetch all tags and associated objects */
  tags?: boolean;
  /** do not fetch all tags (--no-tags) */
  n?: boolean;
  /** number of submodules fetched in parallel */
  jobs?: string;
  /** modify the refspec to place all refs within refs/prefetch/ */
  prefetch?: boolean;
  /** prune remote-tracking branches no longer on remote */
  prune?: boolean;
  /** prune local tags no longer on remote and clobber changed tags */
  pruneTags?: boolean;
  recurseSubmodules?: boolean;
  /** dry run */
  dryRun?: boolean;
  /** machine-readable output */
  porcelain?: boolean;
  /** write fetched references to the FETCH_HEAD file */
  writeFetchHead?: boolean;
  /** keep downloaded pack */
  keep?: boolean;
  /** allow updating of HEAD ref */
  updateHeadOk?: boolean;
  /** force progress reporting */
  progress?: boolean;
  /** deepen history of shallow clone */
  depth?: string;
  shallowSince?: string;
  shallowExclude?: string;
  /** deepen history of shallow clone */
  deepen?: string;
  /** convert to a complete repository */
  unshallow?: boolean;
  /** re-fetch without negotiating common commits */
  refetch?: boolean;
  /** accept refs that update .git/shallow */
  updateShallow?: boolean;
  /** specify fetch refmap */
  refmap?: string;
  serverOption?: string;
  /** use IPv4 addresses only */
  ipv4?: boolean;
  /** use IPv6 addresses only */
  ipv6?: boolean;
  negotiationTip?: string;
  /** do not fetch a packfile; instead, print ancestors of negotiation tips */
  negotiateOnly?: boolean;
  /** object filtering */
  filter?: string;
  /** run 'maintenance --auto' after fetching */
  autoMaintenance?: boolean;
  /** run 'maintenance --auto' after fetching */
  autoGc?: boolean;
  showForcedUpdates?: boolean;
  /** write the commit-graph after fetching */
  writeCommitGraph?: boolean;
  /** accept refspecs from stdin */
  stdin?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git fetch
 * Download objects and refs from another repository
 */
export const fetch = (options: FetchOptions = {}): Promise<CommandResult> =>
  run(["fetch"], options);

interface PullOptions {
  /** be more verbose */
  verbose?: boolean;
  /** be more quiet */
  quiet?: boolean;
  /** force progress reporting */
  progress?: boolean;
  recurseSubmodules?: boolean;
  rebase?: boolean;
  /** do not show a diffstat at the end of the merge */
  n?: boolean;
  /** show a diffstat at the end of the merge */
  stat?: boolean;
  /** add (at most <n>) entries from shortlog to merge commit message */
  log?: boolean;
  /** add a Signed-off-by trailer */
  signoff?: boolean;
  /** create a single commit instead of doing a merge */
  squash?: boolean;
  /** perform a commit if the merge succeeds (default) */
  commit?: boolean;
  /** edit message before committing */
  edit?: boolean;
  /** how to strip spaces and #comments from message */
  cleanup?: string;
  /** allow fast-forward */
  ff?: boolean;
  /** abort if fast-forward is not possible */
  ffOnly?: boolean;
  /** control use of pre-merge-commit and commit-msg hooks */
  verify?: boolean;
  /** verify that the named commit has a valid GPG signature */
  verifySignatures?: boolean;
  /** automatically stash/stash pop before and after */
  autostash?: boolean;
  strategy?: string;
  strategyOption?: string;
  gpgSign?: boolean;
  allowUnrelatedHistories?: boolean;
  /** fetch from all remotes */
  all?: boolean;
  /** append to .git/FETCH_HEAD instead of overwriting */
  append?: boolean;
  /** path to upload pack on remote end */
  uploadPack?: string;
  /** force overwrite of local branch */
  force?: boolean;
  /** fetch all tags and associated objects */
  tags?: boolean;
  /** prune remote-tracking branches no longer on remote */
  prune?: boolean;
  /** number of submodules pulled in parallel */
  jobs?: boolean;
  /** dry run */
  dryRun?: boolean;
  /** keep downloaded pack */
  keep?: boolean;
  /** deepen history of shallow clone */
  depth?: string;
  shallowSince?: string;
  shallowExclude?: string;
  /** deepen history of shallow clone */
  deepen?: string;
  /** convert to a complete repository */
  unshallow?: boolean;
  /** accept refs that update .git/shallow */
  updateShallow?: boolean;
  /** specify fetch refmap */
  refmap?: string;
  serverOption?: string;
  /** use IPv4 addresses only */
  ipv4?: boolean;
  /** use IPv6 addresses only */
  ipv6?: boolean;
  negotiationTip?: string;
  showForcedUpdates?: boolean;
  /** set upstream for git pull/fetch */
  setUpstream?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git pull
 * Fetch from and integrate with another repository or a local branch
 */
export const pull = (options: PullOptions = {}): Promise<CommandResult> => run(["pull"], options);

interface PushOptions {
  /** be more verbose */
  verbose?: boolean;
  /** be more quiet */
  quiet?: boolean;
  /** repository */
  repo?: string;
  /** push all branches */
  all?: boolean;
  /** alias of --all */
  branches?: boolean;
  /** mirror all refs */
  mirror?: boolean;
  /** delete refs */
  delete?: boolean;
  /** push tags (can't be used with --all or --branches or --mirror) */
  tags?: boolean;
  /** dry run */
  dryRun?: boolean;
  /** machine-readable output */
  porcelain?: boolean;
  /** force updates */
  force?: boolean;
  forceWithLease?: boolean;
  /** require remote updates to be integrated locally */
  forceIfIncludes?: boolean;
  recurseSubmodules?: boolean;
  /** use thin pack */
  thin?: boolean;
  receivePack?: string;
  exec?: string;
  /** set upstream for git pull/status */
  setUpstream?: boolean;
  /** force progress reporting */
  progress?: boolean;
  /** prune locally removed refs */
  prune?: boolean;
  /** bypass pre-push hook */
  noVerify?: boolean;
  /** push missing but relevant tags */
  followTags?: boolean;
  signed?: boolean;
  /** request atomic transaction on remote side */
  atomic?: boolean;
  pushOption?: string;
  /** use IPv4 addresses only */
  ipv4?: boolean;
  /** use IPv6 addresses only */
  ipv6?: boolean;
  _?: string | string[];
  [key: string]: unknown;
}

/** git push
 * Update remote refs along with associated objects
 */
export const push = (options: PushOptions = {}): Promise<CommandResult> => run(["push"], options);

/** Run git directly */
export const git = (options: Record<string, unknown> = {}): Promise<CommandResult> =>
  run([], options);

export default git;
